services:
  - type: web
    name: rx8-backend-ws
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker server:app
    plan: free
